# Generated by Django 5.2.9 on 2025-12-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("signup_date", models.DateField(blank=True, null=True)),
                ("last_active_date", models.DateField(blank=True, null=True)),
                (
                    "subscription_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("monthly_spend", models.FloatField(blank=True, null=True)),
                ("feature_usage_score", models.FloatField(blank=True, null=True)),
                ("churned", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "external_id")},
            },
        ),
    ]
