# Generated by Django 5.2.9 on 2025-12-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_churnprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="churnprediction",
            name="recommended_action",
            field=models.CharField(default="No action needed", max_length=255),
        ),
        migrations.AddField(
            model_name="churnprediction",
            name="revenue_at_risk",
            field=models.FloatField(default=0.0),
        ),
    ]
