# Generated by Django 5.2.9 on 2025-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_churnprediction_recommended_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churnprediction",
            name="days_in_risk",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="churnprediction",
            name="early_warning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="churnprediction",
            name="risk_trend",
            field=models.CharField(default="new", max_length=20),
        ),
    ]
